name: CI
on:
  push:
  branches: [main]
  workflow_dispatch:
  
job:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      - name: Greet user
      run: echo welcome to Actions
    
  
  
